apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 encoded "rootpassword"
  MYSQL_DATABASE: bWVkaWNhbF9hcHBvaW50bWVudHM=  # base64 encoded "medical_appointments"
  MYSQL_USER: c3RyYXBpX2FkbWlu  # base64 encoded "strapi_admin"
  MYSQL_PASSWORD: YWRtaW4=  # base64 encoded "admin"